import Image from "next/image";
import profilePhoto from "./cemilture.jpg";
import Link from "next/link";

export const metadata = {
  title: "Manage Courses",
  description: "Generated by create next app",
};

const DashboardPage = ({ children }) => {
  const handleLogout = async () => {
    // const response = NextResponse.json("token");
    // response.cookies.delete("token");
    // return response;
    // Delete the 'token' cookie
    document.cookie = "token=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/";

    // Redirect to the login page
    window.location.href = "/login";
  };

  return (
    <div className="min-h-screen flex bg-gray-100">
      {/* Sidebar */}
      <div className="w-1/5 bg-gray-800 text-white p-4">
        <p className="text-lg font-semibold">Manage Courses</p>
        <div className="text-center mb-24">
          <Image
            className="rounded-full mx-auto"
            src={profilePhoto}
            alt="My Profile Photo"
            width={100}
            height={100}
          />
          <p className="mt-2 text-sm">Admin</p>
        </div>
        <div className="space-y-2">
          <ul>
            <li>
              <Link
                className="text-gray-300 hover:text-white"
                href="/dashboard"
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                className="text-gray-300 hover:text-white"
                href="/dashboard/course"
              >
                Course
              </Link>
            </li>
            <li>
              <Link
                className="text-gray-300 hover:text-white"
                href="/dashboard/students"
              >
                Student
              </Link>
            </li>
            <li>
              <Link
                className="text-gray-300 hover:text-white"
                href="/dashboard/payment"
              >
                Payment
              </Link>
            </li>
            <li>
              <Link
                className="text-gray-300 hover:text-white"
                href="/dashboard/report"
              >
                Report
              </Link>
            </li>
            <li>
              <Link
                className="text-gray-300 hover:text-white"
                href="/dashboard/settings"
              >
                Settings
              </Link>
            </li>
          </ul>
        </div>
        <div className="mt-96">
          <button
            onClick={handleLogout}
            className="bg-red-500 text-white py-2 px-4 rounded-md hover:bg-red-600 focus:outline-none focus:ring focus:border-blue-300"
          >
            Logout
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 p-8">{children}</div>
    </div>
  );
};

export default DashboardPage;
